In [1]:
#Importing the needed libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel(r'C:/Users/Dell/Desktop/Assignments/Clustering/EastWestAirlines.xlsx',sheet_name='data')
data.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [14]:
#Dropping unnecessary columns
df = data.drop(['ID#','cc1_miles','cc2_miles','cc3_miles','Award?'],axis=1)

In [15]:
array = data.values

In [16]:
array

array([[    1, 28143,     0, ...,     0,  7000,     0],
       [    2, 19244,     0, ...,     0,  6968,     0],
       [    3, 41354,     0, ...,     0,  7034,     0],
       ...,
       [ 4019, 73597,     0, ...,     0,  1402,     1],
       [ 4020, 54899,     0, ...,     1,  1401,     0],
       [ 4021,  3016,     0, ...,     0,  1398,     0]], dtype=int64)

In [17]:
stdscaler = StandardScaler().fit(array)
X = stdscaler.transform(array)

In [18]:
X

array([[-1.73512503e+00, -4.51140783e-01, -1.86298687e-01, ...,
        -3.62167870e-01,  1.39545434e+00, -7.66919299e-01],
       [-1.73426342e+00, -5.39456874e-01, -1.86298687e-01, ...,
        -3.62167870e-01,  1.37995704e+00, -7.66919299e-01],
       [-1.73340181e+00, -3.20031232e-01, -1.86298687e-01, ...,
        -3.62167870e-01,  1.41192021e+00, -7.66919299e-01],
       ...,
       [ 1.72682006e+00, -4.29480975e-05, -1.86298687e-01, ...,
        -3.62167870e-01, -1.31560393e+00,  1.30391816e+00],
       [ 1.72768167e+00, -1.85606976e-01, -1.86298687e-01, ...,
        -9.85033311e-02, -1.31608822e+00, -7.66919299e-01],
       [ 1.72854328e+00, -7.00507951e-01, -1.86298687e-01, ...,
        -3.62167870e-01, -1.31754109e+00, -7.66919299e-01]])

In [19]:
dbscan = DBSCAN(eps=0.8, min_samples=6)
dbscan.fit(X)

DBSCAN(eps=0.8, min_samples=6)

In [20]:
dbscan.labels_

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [21]:
clusters = pd.DataFrame(dbscan.labels_,columns=['Cluster_ID'])
clusters.head()

Cluster_ID
0           0
1           0
2           0
3           0
4          -1

In [23]:
data1 = pd.concat([df,clusters],axis=1)
data1

Balance  Qual_miles  Bonus_miles  Bonus_trans  Flight_miles_12mo  \
0       28143           0          174            1                  0   
1       19244           0          215            2                  0   
2       41354           0         4123            4                  0   
3       14776           0          500            1                  0   
4       97752           0        43300           26               2077   
...       ...         ...          ...          ...                ...   
3994    18476           0         8525            4                200   
3995    64385           0          981            5                  0   
3996    73597           0        25447            8                  0   
3997    54899           0          500            1                500   
3998     3016           0            0            0                  0   

      Flight_trans_12  Days_since_enroll  Cluster_ID  
0                   0               7000           0  
1                   0               6968           0  
2                   0               7034           0  
3                   0               6952           0  
4                   4               6935          -1  
...               ...                ...         ...  
3994                1               1403           1  
3995                0               1395           1  
3996                0               1402           1  
3997                1               1401           0  
3998                0               1398           0  

[3999 rows x 8 columns]

In [24]:
data1.groupby('Cluster_ID').count()

Balance  Qual_miles  Bonus_miles  Bonus_trans  Flight_miles_12mo  \
Cluster_ID                                                                     
-1              919         919          919          919                919   
 0             2159        2159         2159         2159               2159   
 1              878         878          878          878                878   
 2                5           5            5            5                  5   
 3               16          16           16           16                 16   
 4                7           7            7            7                  7   
 5                8           8            8            8                  8   
 6                7           7            7            7                  7   

            Flight_trans_12  Days_since_enroll  
Cluster_ID                                      
-1                      919                919  
 0                     2159               2159  
 1                      878                878  
 2                        5                  5  
 3                       16                 16  
 4                        7                  7  
 5                        8                  8  
 6                        7                  7

In [26]:
data1.groupby('Cluster_ID').agg(['mean']).reset_index()

Cluster_ID        Balance  Qual_miles   Bonus_miles Bonus_trans  \
                       mean        mean          mean        mean   
0         -1  152791.552775  624.389554  34958.247008   19.709467   
1          0   48402.226494    0.463177   7843.012969    7.915702   
2          1   51237.712984    1.708428  20309.629841   11.949886   
3          2  221352.200000    0.000000  12000.000000    3.400000   
4          3  148232.562500    0.000000  60375.625000   14.062500   
5          4   30631.571429    0.000000   7589.142857   12.000000   
6          5   50662.125000    0.000000  58158.000000   17.500000   
7          6   47279.000000    0.000000  18041.857143   33.571429   

  Flight_miles_12mo Flight_trans_12 Days_since_enroll  
               mean            mean              mean  
0       1655.563656        4.813928       4607.618063  
1         80.171839        0.276980       3797.680408  
2        164.247153        0.534169       4465.339408  
3          0.000000        0.000000       5603.200000  
4         62.500000        0.125000       2629.125000  
5          0.000000        0.000000       2266.857143  
6          0.000000        0.000000       2585.250000  
7          0.000000        0.000000       1332.285714

# Inferences
* Qual_miles with the clusters 3 to 7 are zero, showing little similarity
* Cluster -1['Qual_miles'] significantly higher than the rest